package com.example.hybridconnect.presentation.navigation

sealed class Route(val name: String, val title: String) {
    data object SplashScreen : Route("splash-screen", "Splash Screen")
    data object OnboardingScreen1 : Route("onboarding-screen-1", "Onboarding Screen")
    data object OnboardingScreen2 : Route("onboarding-screen-2", "Onboarding Screen 2")
    data object Register : Route("register", "Create Account")
    data object OtpVerification : Route("verify-otp/{email}", "Otp Verification")
    data object PinSetup : Route("setup-pin", "Setup Pin")
    data object PinLogin: Route("pin-login/{email}", "Pin Login")
    data object SimSetup : Route("sim-setup", "Sim Setup")
    data object Home : Route("home", "Home")
    data object Offers : Route("offers", "Offers")
    data object AddOffer : Route("offers/new", "Add Offer")
    data object EditOffer : Route("offers/edit/{offerId}", "Edit Offer")
    data object Settings : Route("settings", "Settings")
    data object TransactionDetails : Route("transactions/{transactionId}", "Transaction Details")
    data object MySubscription : Route("my-subscription", "My Subscription")
    data object EditProfile : Route("profile/edit", "Edit Profile")
    data object Customers: Route("customers", "My Customers")
    data object QuickDial: Route("quick-dial", "Quick Dial")
    data object SiteLink: Route("site-link", "Site Link")
    data object Login: Route("login", "Login")
    data object PayWithMpesa : Route("payment/mpesa", "Payment")
    data object PayWith: Route("payment", "Pay With")
    data object PayWithAirtime: Route("payment/airtime", "Pay with Airtime")
    data object Transactions: Route("transactions", "Transactions")
    data object AutoReply: Route("auto-reply", "Auto Reply")
    data object RescheduleOffer: Route("transactions/{transactionId}/reschedule", "Reschedule Offer")
    data object EditCustomer: Route("customers/{customerPhone}/edit", "Edit Customer")
    data object EditAutoReplyMessage: Route("auto-reply/{type}/edit", "Edit AutoReply")
    data object ResetPassword: Route("reset-password/{email}", "Reset Password")
    data object CreateSiteLink: Route("site-link/create", "Create SiteLink")
    data object EditSiteLink: Route("site-link/edit", "EditSiteLink")
    data object HybridConnect: Route("hybrid-connect", "Hybrid Connect")
}