package com.example.hybridconnect.domain.enums

enum class AppSetting {
    DB_INITIALIZED,
    RECEIVE_PAYMENTS_VIA_SIM_1,
    RECEIVE_PAYMENTS_VIA_SIM_2,
    DIAL_USSD_VIA_SIM_1,
    DIAL_USSD_VIA_SIM_2,
    PROCESS_MPESA_MESSAGES,
    PROCESS_TILL_MESSAGES,
    PROCESS_SITE_LINK_MESSAGES,
    AUTO_RETRY_PENDING_REQUESTS,
    AUTO_RETRY_SERVICE_UNAVAILABLE_RESPONSE,
    IS_USSD_PROCESSING,
    AGENT_ID,
    ADMIN_PAYMENT_NUMBER,
    ADMIN_SITE_LINK_NUMBER,
    APP_CONNECT_ID,
    MESSAGES_BUFFER_SIZE
}